version: 2.1

executors:
    grid2op-executor:
        docker:
            - image: bdonnot/grid2op:test
        working_directory: /Grid2Op

    python37:
        docker:
            - image: python:3.7-buster
    python38:
        docker:
            - image: python:3.8-buster
    python39:
        docker:
            - image: python:3.9-buster
    python310:
        docker:
            - image: python:3.10-buster
    python311:
        docker:
            - image: python:3.11-buster

jobs:
    test:
        executor: grid2op-executor
        resource_class: medium
        parallelism: 4
        steps:
            - checkout
            - run: apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U pip setuptools wheel
            - run:
                command: |
                  source venv_test/bin/activate
                  pip install -e .[test]
                  export _GRID2OP_FORCE_TEST=1
                  cd grid2op/tests/
                  python3 helper_list_test.py | circleci tests split > /tmp/tests_run
                  python3 -m unittest $(cat /tmp/tests_run)
                  
    install36:
        executor: python36
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U pip setuptools wheel
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U "numpy>=1.18,<1.19"
                    pip install -U .[test]
                    export _GRID2OP_FORCE_TEST=1
                    grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
                   
    install37:
        executor: python37
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U pip setuptools wheel
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.20,<1.21"
                   pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.21,<1.22"
                   pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall

    install38:               
        executor: python38
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.20,<1.21"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.21,<1.22"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.22,<1.23"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.23,<1.24"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall

    install39:
        executor: python39
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   export _GRID2OP_FORCE_TEST=1
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
                   python -m pip install chronix2grid>="1.1.0.post1"
                   python -m pip uninstall -y grid2op
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U .[test]
            - run:
               command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   python -m pip install -U "numpy>=1.20,<1.21"
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.21,<1.22"
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   python -m pip install -U "numpy>=1.22,<1.23"
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   python -m pip install -U "numpy>=1.23,<1.24"
                   grid2op.testinstall
    install310:
        executor: python310
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.21,<1.22"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.22,<1.23"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   python -m pip install -U "numpy>=1.23,<1.24"
                   grid2op.testinstall

workflows:
    version: 2.1
    test:
        jobs:
          - test
    install:
        jobs:
          - install37
          - install38
          - install39
          - install310
